package com.safety_box.communicator.driver.utils;

import java.util.Map;

import static java.util.Map.entry;

public class DataConstants {
    public static final byte BOFCOMCHAR = (byte) 0x1B;
    public static final byte BOFRESPCHAR = (byte) 0x01;
    public static final byte EOFCHAR = (byte) 0x0D;
    public static final byte SOH = (byte) 0x01;
    public static final byte ENDOFTEXT = (byte) 0x03;
    public static final byte SYNC_BYTE = (byte) 0xD0;
    public static final byte SYNC_MASK = (byte) 0xF0;
    public static final byte SYNC_CMD_BYTE = (byte) 0xC0;
    public static final byte RT_BYTE = (byte) 0x80;
    public static final byte RT_BYTE_MASK = (byte) 0xC0;
    public static final byte SC_END_OF_SEQUENCE = (byte) 0xC0;
    public static final byte SC_DATASTREAM_1_4 = (byte) 0xC1;
    public static final byte SC_DATASTREAM_5_8 = (byte) 0xC2;
    public static final byte SC_DATASTREAM_9_12 = (byte) 0xC3;
    public static final byte SC_TX_DATASTREAM_5_8 = (byte) 0xC4;
    public static final byte SC_TX_DATASTREAM_9_12 = (byte) 0xC5;
    public static final byte SC_START_CYCLE = (byte) 0xC6;
    public static final byte SC_CORRUPT_DATA = (byte) 0xCF;

    public static byte[] poll_request_icc_msg = {
            0x51
    };
    public static byte[] poll_request_deviceid = {
            0x52
    };

    public static byte[] poll_request_no_operation = {
            0x30
    };

    public static byte[] poll_request_stop_com = {
            0x55
    };

    public static byte[] poll_request_config_measured_data_codepage1 = {
            0x24
    };

    public static byte[] poll_request_config_measured_data_codepage2 = {
            0x2B
    };

    public static byte [] poll_request_config_alarms_codepage1 = {
            0x27
    };

    public static byte [] poll_request_config_alarms_codepage2 = {
            0x2E
    };

    public static byte[] poll_request_current_date_time = {
            0x28
    };

    public static byte[] poll_request_device_settings = {
            0x29
    };

    public static byte[] poll_request_text_messages = {
            0x2A
    };

    public static byte[] poll_request_real_time_data_config = {
            0x53
    };

    public static byte[] poll_configure_real_time_transmission = {
            0x54
    };

    public static byte[] poll_request_real_time_config_changed = {
            0x56
    };

    public static Map<Byte, String> MedibusXMeasurementCP1 = Map.<Byte, String>ofEntries(
      entry((byte)0x00, "Accumulated air consumption of the device per case, Air cons"),
      entry((byte)0x01, "Accumulated N2O consumption of the device per case, N2O  cons"),
      entry((byte)0x03, "Expiratory minute volume, MVe"),
      entry((byte)0x04, "Accumulated O2 consumption of the device per case, O2 cons"),
      entry((byte)0x05, "Breathing pressure, PAW"),
      entry((byte)0x06, "Inspiratory minute volume, MVi"),
      entry((byte)0x07, "Dynamic compliance, Cydn"),
      entry((byte)0x08, "CO2 production, R"),
      entry((byte)0x09, "CO2 production, V'CO2"),
      entry((byte)0x0A, "Spontaneous expiratory minute volume, MVespon"),
      entry((byte)0x0B, "Patient airway resistance, Rpat"),
      entry((byte)0x0D, "Mandatory expiratory minute volume, MVemand"),
      entry((byte)0x0E, "Increase of measured CO2 value in phase II of the capnogram, CO2 slope"),
      entry((byte)0x0F, "O2 central gas supply pressure, O2-CGS"),
      entry((byte)0x10, "Increase of measured CO2 value in phase III of the  capnogram, CO2 slope"),
      entry((byte)0x11, "Increase of measured CO2 value in phase III of the  capnogram, CO2 slope"),
      entry((byte)0x12, "Average device flow, Flow device"),
      entry((byte)0x16, "Mandatory tidal volume, VTmand"),
      entry((byte)0x19, "ST deviation in lead I, STI"),
      entry((byte)0x1A, "ST deviation in lead II, STII"),
      entry((byte)0x1B, "Accumulated halothane consumption of the device, Hal cons"),
      entry((byte)0x1C, "Accumulated enflurane consumption of the device, Enf cons"),
      entry((byte)0x1D, "Accumulated isoflurane consumption of the device, Iso cons"),
      entry((byte)0x1E, "Accumulated desflurane consumption of the device, Des cons"),
      entry((byte)0x1F, "Accumulated sevoflurane consumption of the device, Sev  cons"),
      entry((byte)0x21, "Cardiac index, CI"),
      entry((byte)0x22, "Stroke volume, SV"),
      entry((byte)0x23, "Stroke index, SVI"),
      entry((byte)0x24, "Left ventricular stroke work index, LVSWI"),
      entry((byte)0x25, "Right ventricular stroke work index, RVSWI"),
      entry((byte)0x26, "Systemic vascular resistance, SVR"),
      entry((byte)0x27, "Accumulated gas consumption of the device, Gas cons"),
      entry((byte)0x28, "Therapy case duration, Tcase"),
      entry((byte)0x2A, "Correlation factor, r2"),
      entry((byte)0x2B, "Left ventricular pressure - diastolic, LV D"),
      entry((byte)0x2C, "Left ventricular pressure - systolic, LV S"),
      entry((byte)0x2D, "Left ventricular pressure - mean, LV M"),
      entry((byte)0x2E, "Right ventricular pressure - diastolic, RV D"),
      entry((byte)0x2F, "Right ventricular pressure - systolic, RV S"),
      entry((byte)0x30, "Right ventricular pressure - mean, RV M"),
      entry((byte)0x31, "General diastolic pressure (channel 1), GP1 D"),
      entry((byte)0x32, "General systolic pressure (channel 1), GP1 S"),
      entry((byte)0x33, "General mean pressure (channel 1), GP1 M"),
      entry((byte)0x34, "General diastolic pressure (channel 2), GP2 D"),
      entry((byte)0x35, "General systolic pressure (channel 2), GP2 S"),
      entry((byte)0x36, "General mean pressure (channel 2), GP2 M"),
      entry((byte)0x37, "Intracranial pressure, ICP"),
      entry((byte)0x38, "Cerebral perfusion pressure, CPP"),
      entry((byte)0x39, "Left atrial pressure, LA"),
      entry((byte)0x3C, "Mean dynamic compliance, Cdyn mean"),
      entry((byte)0x50, "Inspiratory halothane concentration, inHal"),
      entry((byte)0x51, "End-tidal halothane concentration, etHal"),
      entry((byte)0x52, "Inspiratory enflurane concentration, inEnf"),
      entry((byte)0x53, "End-tidal enflurane concentration, etEnf"),
      entry((byte)0x54, "Inspiratory isoflurane concentration, inIso"),
      entry((byte)0x55, "End-tidal isoflurane concentration, etIso"),
      entry((byte)0x56, "Inspiratory desflurane concentration, inDes"),
      entry((byte)0x57, "End-tidal desflurane concentration, etDes"),
      entry((byte)0x58, "Inspiratory sevoflurane concentration, inSev"),
      entry((byte)0x59, "End-tidal sevoflurane concentration, etSev"),
      entry((byte)0x5A, "Inspiratory concentration of primary agent"),
      entry((byte)0x5B, "End-tidal concentration of primary agent"),
      entry((byte)0x5C, "Inspiratory concentration of secondary agent"),
      entry((byte)0x5D, "End-tidal concentration of secondary agent"),
      entry((byte)0x5E, "ST deviation in lead III, STIII"),
      entry((byte)0x5F, "ST deviation in lead aVL, STaVL"),
      entry((byte)0x60, "ST deviation in lead aVF, STaVF"),
      entry((byte)0x61, "ST deviation in lead aVR, STaVR"),
      entry((byte)0x62, "ST deviation in lead V, STV"),
      entry((byte)0x63, "ST deviation in lead V+, STV+"),
      entry((byte)0x64, "O2 uptake, V'O2"),
      entry((byte)0x65, "Peripheral skin temperature, T Peri"),
      entry((byte)0x66, "Central skin temperature, T Centr"),
      entry((byte)0x68, "Spontaneous inspiratory tidal volume, VTispon"),
      entry((byte)0x69, "Plateau time, Tplat"),
      entry((byte)0x6A, "Mattress temperature, T Matt"),
      entry((byte)0x6B, "Ambient pressure, Pamb"),
      entry((byte)0x6C, "Relative humidity, Humidity"),
      entry((byte)0x6D, "Air temperature, T Air"),
      entry((byte)0x6E, "Radiant warmer power, Heater rad"),
      entry((byte)0x6F, "Spontaneous inspiratory time, Tispon"),
      entry((byte)0x71, "Minimum pressure, Pmin"),
      entry((byte)0x72, "Occlusion pressure in P0.1 maneuver, P0.1"),
      entry((byte)0x73, "Mean airway pressure, Pmean"),
      entry((byte)0x74, "Plateau pressure, Pplat"),
      entry((byte)0x76, "Inspiratory peak flow, Flowipeak"),
      entry((byte)0x78, "Positive end-expiratory pressure, PEEP"),
      entry((byte)0x79, "Intrinsic PEEP, PEEPi"),
      entry((byte)0x7B, "Mandatory respiratory rate, RRmand"),
      entry((byte)0x7C, "Mandatory minute volume, MVmand"),
      entry((byte)0x7D, "Peak inspiratory pressure, PIP"),
      entry((byte)0x7E, "Mandatory tidal volume, VTmand"),
      entry((byte)0x7F, "Spontaneous tidal volume, VTspon"),
      entry((byte)0x81, "Volume trapped in the lung by intrinsic PEEP, Vtrap"),
      entry((byte)0x83, "Mandatory expiratory tidal volume, VTemand"),
      entry((byte)0x84, "Spontaneous expiratory tidal volume, VTespon"),
      entry((byte)0x85, "Mandatory inspiratory tidal volume, VTimand"),
      entry((byte)0x86, "Tidal volume during HFO, VThf"),
      entry((byte)0x88, "Tidal volume, VT"),
      entry((byte)0x89, "Serial dead space volume, Vds"),
      entry((byte)0x8A, "Ratio of serial dead space volume to expiratory tidal volume,  Vds/VTe"),
      entry((byte)0x8B, "Inspiratory tidal volume, VTi"),
      entry((byte)0x8C, "Non-invasive blood pressure - diastolic, NIBP D"),
      entry((byte)0x8D, "Negative inspiratory force, NIF"),
      entry((byte)0x91, "Non-invasive blood pressure - mean, NIBP M"),
      entry((byte)0x92, "Time since last non-invasive blood pressure measurement,  Tnibp"),
      entry((byte)0x96, "Non-invasive blood pressure - systolic, NIBP S"),
      entry((byte)0x9B, "Cardiac output, C.O."),
      entry((byte)0x9C, "Total halothane uptake, Hal tot"),
      entry((byte)0x9D, "Total desflurane uptake, Des tot"),
      entry((byte)0x9E, "Total isoflurane uptake, Iso tot"),
      entry((byte)0x9F, "Total sevoflurane uptake, Sev tot"),
      entry((byte)0xA0, "Total enflurane uptake, Enf tot"),
      entry((byte)0xA1, "Pulmonary arterial pressure - diastolic, PA D"),
      entry((byte)0xA2, "Duration of phototherapy, Dur PT"),
      entry((byte)0xA3, "Irradiance during phototherapy, Irradiance PT"),
      entry((byte)0xA5, "Central venous pressure, CVP"),
      entry((byte)0xA6, "Pulmonary arterial pressure - mean, PA M"),
      entry((byte)0xA7, "Right atrial pressure, RA"),
      entry((byte)0xAB, "Pulmonary arterial pressure - systolic, PA S"),
      entry((byte)0xAC, "MAC multiple derived from inspiratory concentrations, inxMAC"),
      entry((byte)0xAD, "MAC multiple derived from expiratory concentrations, xMAC"),
      entry((byte)0xAE, "Inspiratory desflurane concentration, inDes"),
      entry((byte)0xAF, "End-tidal desflurane concentration, etDes"),
      entry((byte)0xB0, "Inspiratory sevoflurane concentration, inSev"),
      entry((byte)0xB1, "End-tidal sevoflurane concentration, etSev"),
      entry((byte)0xB2, "Leakage of the breathing system"),
      entry((byte)0xB3, "Leakage minute volume in % of inspiratory minute volume, %  leak"),
      entry((byte)0xB4, "Respiratory rate based on pressure measurement, RRp"),
      entry((byte)0xB5, "Spontaneous respiratory rate, RRspon"),
      entry((byte)0xB6, "Spontaneous breathing portion of minute volume, % MVspon"),
      entry((byte)0xB7, "Spontaneous minute volume, MVspon"),
      entry((byte)0xB9, "Minute volume, MV"),
      entry((byte)0xBD, "Apnea duration"),
      entry((byte)0xBE, "Temperature 2, T2"),
      entry((byte)0xC0, "Oxygen concentration, O2"),
      entry((byte)0xC1, "Airway temperature, T Airw"),
      entry((byte)0xC2, "Skin temperature difference, ΔT Skin"),
      entry((byte)0xC3, "Temperature 1, T1"),
      entry((byte)0xC4, "Inspiratory/expiratory oxygen concentration difference, ΔO2"),
      entry((byte)0xC5, "Pulmonary wedge pressure, PWP"),
      entry((byte)0xC6, "Battery capacity"),
      entry((byte)0xC7, "Insp. O2 accuracy, O2bias"),
      entry((byte)0xC8, "Arterial diastolic pressure, ART D"),
      entry((byte)0xC9, "Rapid shallow breathing index, RSBI"),
      entry((byte)0xCD, "Arterial mean pressure, ART M"),
      entry((byte)0xCE, "Perfusion index, PI"),
      entry((byte)0xD0, "Respiratory rate of triggered, mandatory breaths, RRtrig"),
      entry((byte)0xD2, "Arterial systolic pressure, ART S"),
      entry((byte)0xD5, "Respiratory rate based on CO2 measurement, RRc"),
      entry((byte)0xD6, "Respiratory rate, RR"),
      entry((byte)0xD7, "Respiratory rate based on volume/flow measurement, RRf"),
      entry((byte)0xD9, "Respiratory rate, RR"),
      entry((byte)0xDA, "Inspiratory CO2 concentration, inCO2"),
      entry((byte)0xDB, "End-tidal CO2 concentration, etCO2"),
      entry((byte)0xDC, "Heart rate, HR"),
      entry((byte)0xDD, "N2O fresh-gas flow, FG V'N2O"),
      entry((byte)0xDE, "Air fresh-gas flow, FG V'Air"),
      entry((byte)0xE1, "Pulse Rate, PLS"),
      entry((byte)0xE2, "Oxygen fresh-gas flow, FG V'O2"),
      entry((byte)0xE3, "End-tidal CO2 concentration, etCO2"),
      entry((byte)0xE4, "Light level, Light"),
      entry((byte)0xE5, "Inspiratory CO2 concentration, inCO2"),
      entry((byte)0xE6, "End-tidal CO2 concentration, etCO2"),
      entry((byte)0xE7, "Measured I : E I part"),
      entry((byte)0xE8, "Measured I : E E part"),
      entry((byte)0xE9, "Inspiratory concentration of primary agent"),
      entry((byte)0xEA, "End-tidal concentration of primary agent"),
      entry((byte)0xEB, "Oxygen saturation from pulse oximetry, SpO2"),
      entry((byte)0xEC, "Noise level, Noise"),
      entry((byte)0xED, "Inspiratory concentration of secondary agent"),
      entry((byte)0xEE, "End-tidal concentration of secondary agent"),
      entry((byte)0xEF, "End-tidal oxygen concentration, etO2"),
      entry((byte)0xF0, "Inspiratory oxygen fraction, FiO2"),
      entry((byte)0xF1, "Convective heater power, Heater conv"),
      entry((byte)0xF2, "Body weight, BW"),
      entry((byte)0xF3, "Weight date"),
      entry((byte)0xF4, "Inspiratory halothane concentration, inHal"),
      entry((byte)0xF5, "End-tidal halothane concentration, etHal"),
      entry((byte)0xF6, "Inspiratory enflurane concentration, inEnf"),
      entry((byte)0xF7, "End-tidal enflurane concentration, etEnf"),
      entry((byte)0xF8, "Inspiratory isoflurane concentration, inIso"),
      entry((byte)0xF9, "End-tidal isoflurane concentration, etIso"),
      entry((byte)0xFA, "Weight sample age"),
      entry((byte)0xFB, "Inspiratory N2O concentration, inN2O"),
      entry((byte)0xFC, "End-tidal N2O concentration, etN2O"),
      entry((byte)0xFF, "Inspiratory CO2 concentration, inCO2")
    );

    public static Map<Byte, String> MedibusXMeasurementCP2 = Map.<Byte, String>ofEntries(
      entry((byte)0x00, "Spontaneous tidal volume, VTspon"),
      entry((byte)0x03, "Pressure amplitude during HFO, ΔPhf"),
      entry((byte)0x04, "Inspiratory part of I:E ratio during spontaneous breathing, I  (I:Espon)"),
      entry((byte)0x05, "Expiratory part of I:E ratio during spontaneous breathing, E  (I:Espon)"),
      entry((byte)0x06, "Elastance, E"),
      entry((byte)0x07, "Time constant, TC"),
      entry((byte)0x09, "Expiratory time constant, TCe"),
      entry((byte)0x0A, "Static compliance, Cstat"),
      entry((byte)0x0B, "Ratio of compliance during the last 20 % of inspiration over  dynamic compliance, C20/Cdyn"),
      entry((byte)0x0C, "CO2 elimination coefficient during HFO, DCO2"),
      entry((byte)0x0D, "Rapid shallow breathing index, RSBI"),
      entry((byte)0x0E, "Train-of-four ratio, TOF Ratio"),
      entry((byte)0x0F, "Post-tetanic count, PTC"),
      entry((byte)0x10, "NMT temperature, T NMT"),
      entry((byte)0x11, "Single twitch mode, Single"),
      entry((byte)0x12, "Train-of-four count, TOF Cnt"),
      entry((byte)0x13, "Bispectral index, BIS"),
      entry((byte)0x14, "Electromyogram power, EMG"),
      entry((byte)0x15, "Signal quality index, SQI"),
      entry((byte)0x16, "Burst suppression ratio (BIS), BSR"),
      entry((byte)0x17, "Spectral edge frequency 95, SEF95"),
      entry((byte)0x18, "Burst count (BIS), BCT"),
      entry((byte)0x19, "Total power (BIS), EEG Pwr"),
      entry((byte)0x1A, "Goal for Δpressure support in SmartCare, SC-ΔPsupp goal"),
      entry((byte)0x1B, "Rated Δpressure support by internal controller in SmartCare, SC-ΔPsupp rated"),
      entry((byte)0x1C, "Duration of session (hours) in SmartCare, SC-duration"),
      entry((byte)0x1D, "Duration of session (minutes) in SmartCare, SC-duration"),
      entry((byte)0x1E, "Spontaneous respiratory rate in SmartCare, SC-RRspon"),
      entry((byte)0x1F, "Tidal volume in SmartCare, SC-VT"),
      entry((byte)0x21, "Expiratory tidal volume, VTe"),
      entry((byte)0x22, "Inspiratory tidal volume, VTi"),
      entry((byte)0x23, "End-inspiratory pressure, EIP"),
      entry((byte)0x24, "Effective expiratory time during APRV/AutoRelease, Tlow"),
      entry((byte)0x25, "CO2 production volume per breath, VTCO2"),
      entry((byte)0x28, "End-tidal CO2 concentration in SmartCare, SC-etCO2"),
      entry((byte)0x29, "ST deviation in lead I, STI"),
      entry((byte)0x2A, "ST deviation in lead II, STII"),
      entry((byte)0x2B, "ST deviation in lead III, STIII"),
      entry((byte)0x2C, "ST deviation in lead aVL, STaVL"),
      entry((byte)0x2D, "ST deviation in lead aVF, STaVF"),
      entry((byte)0x2E, "ST deviation in lead aVR, STaVR"),
      entry((byte)0x2F, "ST deviation in lead V, STV"),
      entry((byte)0x30, "ST deviation in lead V+, STV+"),
      entry((byte)0x31, "Upper pressure level during APRV, Phigh"),
      entry((byte)0x32, "Lower pressure level during APRV, Plow"),
      entry((byte)0x33, "Spontaneous mean tidal volume, VTspon mean"),
      entry((byte)0x34, "Inspiratory spontaneous mean tidal volume, VTispon mean"),
      entry((byte)0x35, "Expiratory spontaneous mean Tidal Volume, VTespon mean"),
      entry((byte)0x36, "Tidal volume per kg ideal body weight, VT/IBW"),
      entry((byte)0x37, "Leakage minute volume, MVleak"),
      entry((byte)0x38, "Inspiratory time, Ti"),
      entry((byte)0x39, "Leakage of breathing system, bag and hoses in Man/Spont"),
      entry((byte)0x3A, "Compliance of the breathing system including patient circuit,  Cbs+hose"),
      entry((byte)0x3B, "Compliance of the breathing hoses, Chose"),
      entry((byte)0x3C, "Adaption Time, Tadapt"),
      entry((byte)0x3D, "Applied upper limit for the VT target range in Smart Ventilation  Control, SVC-VT high"),
      entry((byte)0x3E, "Tidal volume calculated by Smart Ventilation Control, SVC-VT"),
      entry((byte)0x3F, "Applied lower limit for the VT target range in Smart Ventilation  Control, SVC-VT low"),
      entry((byte)0x40, "Applied upper limit for the etCO2 target range in Smart  Ventilation Control, SVC-etCO2 high"),
      entry((byte)0x41, "End-tidal carbon dioxide concentration calculated by Smart  Ventilation Control, SVC-etCO2"),
      entry((byte)0x42, "Applied lower limit for the etCO2 target range in Smart  Ventilation Control, SVC-etCO2 low"),
      entry((byte)0x43, "Total respiratory rate in Smart Ventilation Control, SVCRRTotal"),
      entry((byte)0x44, "Spontaneous respiratory rate set by Smart Ventilation Control,  SVC-RRspon"),
      entry((byte)0x45, "Relative pressure support above PEEP set by Smart  Ventilation Control, SVC-ΔPsupp"),
      entry((byte)0x46, "Inspiratory pressure set by Smart Ventilation Control, SVCPInsp"),
      entry((byte)0x47, "Respiratory rate set by Smart Ventilation Control, SVC-RR"),
      entry((byte)0x48, "Minimum respiratory rate set by Smart Ventilation Control,  SVC-RRmin"),
      entry((byte)0x49, "Inspiratory time set by Smart Ventilation Control, SVC-TI"),
      entry((byte)0x4A, "Flow trigger set by Smart Ventilation Control, SVC-Trigger"),
      entry((byte)0x4B, "currently active ventilation goal of Smart Ventilation Control,  Ventilation goal"),
      entry((byte)0x4C, "Current state of Smart Ventilation Control, SVC state"),
      entry((byte)0x4D, "VT classification by Smart Ventilation Control, SVC VT class"),
      entry((byte)0x4E, "EtCO2 classification by Smart Ventilation Control, SVC etCO2  class"),
      entry((byte)0x4F, "Therapy phase of Smart Ventilation Control, SVC phase"),
      entry((byte)0x50, "Ventilation mode used by Smart Ventilation Control, SVC  mode"),
      entry((byte)0x51, "Spontaneous breathing detection of Smart Ventilation Control,  SVC spont. breathing"),
      entry((byte)0x52, "Resistance of the breathing hoses, Rhose"),
      entry((byte)0x53, "Difference between inspired and expired tidal volume (VTi VTe), ΔVT")
    );

    public static Map<Byte, String> MedibusXRealTimeData = Map.<Byte, String>ofEntries(
      entry((byte)0x00, "Airway pressure, Paw"),
      entry((byte)0x01, "Flow (inspiratory/expiratory), Flow"),
      entry((byte)0x02, "Oxygen saturation pulse, Pleth"),
      entry((byte)0x03, "Respiratory volume since start of inspiration, Volume"),
      entry((byte)0x05, "Oxygen concentration (inspiratory/expiratory), O2"),
      entry((byte)0x06, "CO2 concentration, CO2 (mmHg)"),
      entry((byte)0x07, "CO2 concentration, CO2 (kPa)"),
      entry((byte)0x08, "CO2 concentration, CO2 (%)"),
      entry((byte)0x0A, "Concentration of primary agent (inspiratory/expiratory)"),
      entry((byte)0x0B, "Halothane concentration (inspiratory/expiratory), Hal"),
      entry((byte)0x0C, "Enflurane concentration (inspiratory/expiratory), Enf"),
      entry((byte)0x0D, "Isoflurane concentration (inspiratory/expiratory), Iso"),
      entry((byte)0x0E, "Desflurane concentration (inspiratory/expiratory), Des"),
      entry((byte)0x0F, "Sevoflurane concentration (inspiratory/expiratory), Sev"),
      entry((byte)0x1C, "Tracheal pressure, Ptrach"),
      entry((byte)0x1E, "Inspiratory device flow, Flow dev insp"),
      entry((byte)0x2A, "Concentration of primary agent (inspiratory/expiratory) (kPa)"),
      entry((byte)0x2B, "Halothane concentration (inspiratory/expiratory), Hal (kPa)"),
      entry((byte)0x2C, "Enflurane concentration (inspiratory/expiratory), Enf"),
      entry((byte)0x2D, "Isoflurane concentration (inspiratory/expiratory), Iso"),
      entry((byte)0x2E, "Desflurane concentration (inspiratory/expiratory), Des"),
      entry((byte)0x2F, "Sevoflurane concentration (inspiratory/expiratory), Sev")
    );

    public static Map<Byte, String> MedibusXAlarmsCP1 = Map.<Byte, String>ofEntries(
      entry((byte)0x00, "Apnea by different or undefined sources"),
      entry((byte)0x01, "No SpO2 pulse"),
      entry((byte)0x02, "SpO2 pulse < low limit"),
      entry((byte)0x03, "General systolic pressure (channel 1) > high limit"),
      entry((byte)0x04, "General systolic pressure (channel 1) < low limit"),
      entry((byte)0x05, "Heart rate / pulse < low limit"),
      entry((byte)0x06, "Pulmonary arterial pressure - systolic > high limit"),
      entry((byte)0x07, "SpO2 < low limit"),
      entry((byte)0x08, "Inspiratory oxygen concentration < low limit"),
      entry((byte)0x09, "Inspiratory halothane concentration > high limit"),
      entry((byte)0x0A, "Pulmonary arterial pressure - diastolic > high limit"),
      entry((byte)0x0B, "Inspiratory enflurane concentration > high limit"),
      entry((byte)0x0C, "Inspiratory isoflurane > high limit"),
      entry((byte)0x0D, "Apnea - detected by CO2 monitoring"),
      entry((byte)0x0E, "Apnea - detected by volume monitoring"),
      entry((byte)0x0F, "Apnea - detected by pressure monitoring"),
      entry((byte)0x10, "Airway pressure > high limit"),
      entry((byte)0x11, "Check fresh-gas setting"),
      entry((byte)0x12, "Check air supply"),
      entry((byte)0x13, "Check O2 supply"),
      entry((byte)0x14, "Pulmonary arterial pressure - mean > high limit"),
      entry((byte)0x15, "Pulmonary arterial pressure - systolic < low limit"),
      entry((byte)0x16, "Pulmonary arterial pressure - diastolic < low limit"),
      entry((byte)0x17, "Pulmonary arterial pressure - mean < low limit"),
      entry((byte)0x18, "Expiratory pressure > high limit"),
      entry((byte)0x19, "Minute volume < low limit"),
      entry((byte)0x1A, "NIBP systolic < low limit"),
      entry((byte)0x1B, "NIBP diastolic < low limit"),
      entry((byte)0x1C, "Arterial systolic pressure < low limit"),
      entry((byte)0x1D, "General diastolic pressure (channel 1) > high limit"),
      entry((byte)0x1E, "SpO2 pulse > high limit"),
      entry((byte)0x1F, "Inspiratory sevoflurane concentration > high limit"),
      entry((byte)0x20, "General diastolic pressure (channel 1) < low limit"),
      entry((byte)0x21, "Heart rate > high limit"),
      entry((byte)0x22, "SpO2 > high limit"),
      entry((byte)0x23, "NIBP systolic > high limit"),
      entry((byte)0x24, "Inspiratory desflurane concentration > high limit"),
      entry((byte)0x25, "Arterial systolic pressure > high limit"),
      entry((byte)0x26, "General mean pressure (channel 1) > high limit"),
      entry((byte)0x27, "End-tidal CO2 < low limit"),
      entry((byte)0x28, "End-tidal CO2 > high limit"),
      entry((byte)0x29, "Inspiratory halothane concentration < low limit"),
      entry((byte)0x2A, "Inspiratory enflurane concentration < low limit"),
      entry((byte)0x2B, "Inspiratory isoflurane < low limit"),
      entry((byte)0x2C, "Inspiratory desflurane < low limit"),
      entry((byte)0x2D, "NIBP diastolic > high limit"),
      entry((byte)0x2E, "Temperature 1 < low limit"),
      entry((byte)0x2F, "Temperature 2 < low limit"),
      entry((byte)0x30, "Air temperature high"),
      entry((byte)0x31, "General mean pressure (channel 1) < low limit"),
      entry((byte)0x32, "Inspiratory sevoflurane < low limit"),
      entry((byte)0x33, "Volume not constant"),
      entry((byte)0x35, "SpO2 sensor disconnected, not supported or fault"),
      entry((byte)0x36, "CO2 Filter check failed"),
      entry((byte)0x37, "Inspiratory oxygen concentration > high limit"),
      entry((byte)0x38, "General systolic pressure (channel 2) > high limit"),
      entry((byte)0x39, "General systolic pressure (channel 2) < low limit"),
      entry((byte)0x3A, "Pressure support terminated by time"),
      entry((byte)0x3B, "Oxygen analyzer not calibrated"),
      entry((byte)0x3C, "Inspiratory CO2 > high limit"),
      entry((byte)0x3D, "CO2 patient sensor line blocked"),
      entry((byte)0x3E, "CO2 zero-calibration requested"),
      entry((byte)0x3F, "NIBP mean < low limit"),
      entry((byte)0x40, "General diastolic pressure (channel 2) > high limit"),
      entry((byte)0x41, "NIBP mean > high limit"),
      entry((byte)0x42, "Check flow sensor"),
      entry((byte)0x43, "O2 sensor inoperable"),
      entry((byte)0x44, "General diastolic pressure (channel 2) < low limit"),
      entry((byte)0x45, "General mean pressure (channel 2) > high limit"),
      entry((byte)0x46, "Temperature 1 failure"),
      entry((byte)0x47, "Temperature 2 failure"),
      entry((byte)0x48, "Air temperature measurement failure"),
      entry((byte)0x49, "Check NIBP cuff size!"),
      entry((byte)0x4A, "Unable to take NiBP measurement"),
      entry((byte)0x4B, "Battery capacity low"),
      entry((byte)0x4C, "General mean pressure (channel 2) < low limit"),
      entry((byte)0x4D, "Left ventricular pressure - systolic > high limit"),
      entry((byte)0x4E, "Left ventricular pressure - systolic < low limit"),
      entry((byte)0x4F, "LL electrode failure"),
      entry((byte)0x50, "LA electrode failure"),
      entry((byte)0x51, "RA electrode failure"),
      entry((byte)0x52, "Left ventricular pressure - diastolic > high limit"),
      entry((byte)0x53, "ECG S-T analysis impossible"),
      entry((byte)0x54, "Central venous pressure < low limit"),
      entry((byte)0x55, "Central venous pressure > high limit"),
      entry((byte)0x56, "Left ventricular pressure - diastolic < low limit"),
      entry((byte)0x57, "CO2 alarm disabled"),
      entry((byte)0x58, "No agent compensation"),
      entry((byte)0x59, "No carrier-gas compensation"),
      entry((byte)0x5A, "Cardiovasc. alarms disabled alarms off"),
      entry((byte)0x5B, "Pulse oximeter alarm disabled"),
      entry((byte)0x5C, "Left ventricular pressure - mean > high limit"),
      entry((byte)0x5E, "Volume alarm disabled"),
      entry((byte)0x60, "NIBP hose unplugged"),
      entry((byte)0x61, "Left ventricular pressure - mean < low limit"),
      entry((byte)0x62, "Left atrial pressure > high limit"),
      entry((byte)0x63, "Left atrial pressure < low limit"),
      entry((byte)0x64, "Clean CO2 sensor (window occluded)"),
      entry((byte)0x65, "Speaker failure"),
      entry((byte)0x66, "Mixed agent detected"),
      entry((byte)0x67, "Multi-gas monitor device failure"),
      entry((byte)0x68, "SpO2 device failure"),
      entry((byte)0x69, "N2O-measurement inoperable"),
      entry((byte)0x6A, "CO2 device failure"),
      entry((byte)0x6B, "Air temperature low"),
      entry((byte)0x6C, "NiBP device failure"),
      entry((byte)0x6E, "Agent-measurement inoperable"),
      entry((byte)0x6F, "Right ventricular pressure - systolic > high limit"),
      entry((byte)0x70, "Oxygen concentration low"),
      entry((byte)0x71, "Right ventricular pressure - systolic < low limit"),
      entry((byte)0x72, "Right ventricular pressure - diastolic > high limit"),
      entry((byte)0x73, "Right ventricular pressure - diastolic < low limit"),
      entry((byte)0x74, "Right ventricular pressure - mean > high limit"),
      entry((byte)0x75, "Right ventricular pressure - mean < low limit"),
      entry((byte)0x76, "Intracranial pressure > high limit"),
      entry((byte)0x77, "Intracranial pressure < low limit"),
      entry((byte)0x78, "Communication error RS232 port"),
      entry((byte)0x79, "Cerebral perfusion pressure > high limit"),
      entry((byte)0x7A, "Cerebral perfusion pressure < low limit"),
      entry((byte)0x7B, "Hemomed Pod 1 failure"),
      entry((byte)0x7C, "Internal system communication error"),
      entry((byte)0x7D, "Arterial pressure no pulse detected"),
      entry((byte)0x7F, "Problems with intracranial pressure measurement"),
      entry((byte)0x80, "Problems with left atrial pressure measurement"),
      entry((byte)0x81, "Problems with right ventricular pressure measurement"),
      entry((byte)0x82, "Problems with left ventricular pressure measurement"),
      entry((byte)0x83, "Problems with general blood pressure measurement (channel 1)"),
      entry((byte)0x84, "Problems with general blood pressure measurement (channel 2)"),
      entry((byte)0x85, "No pulse detected for right ventricular pressure measurement"),
      entry((byte)0x86, "Arterial mean pressure < low limit"),
      entry((byte)0x87, "Arterial mean pressure > high limit"),
      entry((byte)0x88, "Arterial diastolic pressure < low limit"),
      entry((byte)0x89, "No pulse detected for left ventricular pressure measurement"),
      entry((byte)0x8A, "Arterial diastolic pressure > high limit"),
      entry((byte)0x8B, "No pulse detected for general blood pressure measurement (channel 1)"),
      entry((byte)0x8C, "No pulse detected for general blood pressure measurement (channel 2)"),
      entry((byte)0x90, "Respiratory rate > high limit"),
      entry((byte)0x92, "ECG leads failure"),
      entry((byte)0x94, "S-T segment high alarm"),
      entry((byte)0x95, "Rescue ventilation active"),
      entry((byte)0x96, "Asystoly"),
      entry((byte)0x98, "Apnea detected by respiratory monitoring"),
      entry((byte)0x99, "S-T segment low alarm"),
      entry((byte)0x9A, "Disconnection ventilator / airway pressure < low limit"),
      entry((byte)0x9B, "Minute volume > high limit"),
      entry((byte)0x9E, "Water level low"),
      entry((byte)0x9F, "Problems with respirator"),
      entry((byte)0xA0, "Ventilator Communication lost"),
      entry((byte)0xA1, "Inspiratory O2 measurement inoperable"),
      entry((byte)0xA2, "Flow calibration necessary"),
      entry((byte)0xA3, "Airway pressure negative"),
      entry((byte)0xA4, "Volume measurement inoperable"),
      entry((byte)0xA6, "Check water supply"),
      entry((byte)0xA7, "AutoAdapt active"),
      entry((byte)0xA8, "Oxygen concentration high"),
      entry((byte)0xA9, "Leakage valve blocked"),
      entry((byte)0xAB, "Convective heater failure"),
      entry((byte)0xAC, "Minute volume alarm disabled"),
      entry((byte)0xAD, "Pressure measurement inoperable"),
      entry((byte)0xAE, "Continuous nebulization active"),
      entry((byte)0xAF, "Check watertrap"),
      entry((byte)0xB0, "Check expiratory valve"),
      entry((byte)0xB1, "Hood open - check hood"),
      entry((byte)0xB2, "Weaning temperature not reached"),
      entry((byte)0xB3, "Gas calibration in progress"),
      entry((byte)0xB4, "Heated mattress faulty"),
      entry((byte)0xB5, "Sensor module failure"),
      entry((byte)0xB6, "Warm-up procedure completed"),
      entry((byte)0xB7, "Temperature of ventilator blower too high"),
      entry((byte)0xB8, "Airway temperature measurement inop"),
      entry((byte)0xB9, "Check airway temperature sensor"),
      entry((byte)0xBA, "Airway temperature > high limit"),
      entry((byte)0xBB, "Session cannot be continued. Patient values do not match the guideline"),
      entry((byte)0xBC, "Breathing System not locked"),
      entry((byte)0xBD, "Check O2 supply"),
      entry((byte)0xBE, "O2 measurement inoperable"),
      entry((byte)0xBF, "Weaning procedure failed"),
      entry((byte)0xC0, "Inspiratory O2 < low limit"),
      entry((byte)0xC1, "Flow measurement inoperable"),
      entry((byte)0xC2, "Gas mixing and/or delivery failure"),
      entry((byte)0xC4, "Pressure limited respiratory volume"),
      entry((byte)0xC5, "Weaning procedure completed"),
      entry((byte)0xC7, "Fail to cycle"),
      entry((byte)0xC8, "Gas mixer inoperable"),
      entry((byte)0xC9, "Internal device temperature too high"),
      entry((byte)0xCA, "Problems with fan"),
      entry((byte)0xCB, "Temperature 1 > high limit"),
      entry((byte)0xCC, "Temperature 2 > high limit"),
      entry((byte)0xCD, "O2 measurement temporarily unavailable"),
      entry((byte)0xCE, "N2O measurement temporarily unavailable"),
      entry((byte)0xCF, "Agent measurement temporarily unavailable"),
      entry((byte)0xD0, "V-electrode failure"),
      entry((byte)0xD1, "Patient gas measurement overflow"),
      entry((byte)0xD2, "VFIB / VTACH - arrhythmia detected"),
      entry((byte)0xD3, "Patient misconnected? Patient activity detected at inactive breathing system"),
      entry((byte)0xD5, "Multiple gas measurement values can temporarily not be measured with  accuracy complying to ISO standard."),
      entry((byte)0xD6, "Problems with arterial pressure measurement"),
      entry((byte)0xD7, "Problems with central venous pressure measurement"),
      entry((byte)0xD8, "Agent measurement values can temporarily not be measured with accuracy  complying to ISO standard."),
      entry((byte)0xD9, "CO2 sensor disconnected or fault"),
      entry((byte)0xDA, "PEEP > high limit"),
      entry((byte)0xDB, "SpO2 < desaturation limit"),
      entry((byte)0xDD, "Cardiac output device failure"),
      entry((byte)0xDE, "Cardiac output check injectate probe"),
      entry((byte)0xDF, "Cardiac output transducer fail"),
      entry((byte)0xE0, "SpO2 sensor has detected interference"),
      entry((byte)0xE1, "SpO2 accessory close to expiry"),
      entry((byte)0xE2, "Problems with pulmonary arterial pressure measurement"),
      entry((byte)0xE3, "Pulmonary arterial pressure no pulse detected"),
      entry((byte)0xE4, "N2O measurement values can temporarily not be measured with accuracy  complying to ISO standard."),
      entry((byte)0xE5, "O2 measurement values can temporarily not be measured with accuracy  complying to ISO standard."),
      entry((byte)0xE6, "Air supply pressure > high limit"),
      entry((byte)0xE7, "High O2 supply pressure"),
      entry((byte)0xE8, "Tidal volume > high limit"),
      entry((byte)0xE9, "O2 alarm disabled"),
      entry((byte)0xEB, "CO2 measurement values can temporarily not be measured with accuracy  complying to ISO standard."),
      entry((byte)0xEC, "Gas supply failure"),
      entry((byte)0xED, "Check N2O supply"),
      entry((byte)0xEE, "Two agents detected"),
      entry((byte)0xEF, "Power fail"),
      entry((byte)0xF0, "Skin temperature difference high"),
      entry((byte)0xF1, "Check setting of Pmax"),
      entry((byte)0xF2, "Internal system fault"),
      entry((byte)0xF3, "No fresh gas"),
      entry((byte)0xF4, "O2 safety flow activated"),
      entry((byte)0xF5, "Inspiratory MAC > high limit"),
      entry((byte)0xF6, "Skin temperature difference low"),
      entry((byte)0xF7, "Inspiratory CO2 alarm disabled"),
      entry((byte)0xF8, "Continuous high pressure"),
      entry((byte)0xFA, "Pressure threshold low"),
      entry((byte)0xFB, "Check APL valve"),
      entry((byte)0xFC, "CO2 not calibrated"),
      entry((byte)0xFD, "Battery inoperable"),
      entry((byte)0xFE, "Check cooling"),
      entry((byte)0xFF, "Disconnection ventilator")
    );

    public static Map<Byte, String> MedibusXAlarmsCP2 = Map.<Byte, String>ofEntries(
      entry((byte)0x01, "NiBP did not measure"),
      entry((byte)0x03, "NIBP max. inflation press. exceeded"),
      entry((byte)0x07, "NIBP measurement max time exceeded"),
      entry((byte)0x0B, "NIBP tube blocked"),
      entry((byte)0x0C, "Humidifier inoperable"),
      entry((byte)0x0D, "Humidity low"),
      entry((byte)0x10, "N2O supply pressure > high limit"),
      entry((byte)0x11, "Volatile agent dosage error"),
      entry((byte)0x12, "Volatile agent dosage error and mixer error"),
      entry((byte)0x13, "CPAP pressure not established due to leak. CPAP setting has been disabled."),
      entry((byte)0x15, "Central skin temperature < low limit"),
      entry((byte)0x16, "Central skin temperature > high limit"),
      entry((byte)0x17, "Central skin temperature failure"),
      entry((byte)0x18, "Peripheral skin temperature < low limit"),
      entry((byte)0x19, "Peripheral skin temperature > high limit"),
      entry((byte)0x1A, "Peripheral skin temperature failure"),
      entry((byte)0x1B, "Ambient temperature measurement failure"),
      entry((byte)0x31, "O2 cylinder pressure low"),
      entry((byte)0x32, "O2 cylinder empty or cylinder pressure low"),
      entry((byte)0x33, "O2 cylinder not connected"),
      entry((byte)0x34, "N2O cylinder empty or cylinder pressure low"),
      entry((byte)0x35, "N2O delivery failure"),
      entry((byte)0x36, "O2 delivery failure"),
      entry((byte)0x37, "AIR delivery failure"),
      entry((byte)0x38, "Set fresh-gas flow not attained"),
      entry((byte)0x39, "Internal/external switch valve inoperable"),
      entry((byte)0x3A, "Insp. N2O > high limit"),
      entry((byte)0x3B, "Ambient pressure measurement disturbed or inoperable"),
      entry((byte)0x3C, "SDC certificate cannot be used"),
      entry((byte)0x40, "Agent dosage inoperable"),
      entry((byte)0x41, "Agent reservoir low"),
      entry((byte)0x42, "CO2 sample gas line disconnected"),
      entry((byte)0x43, "Check setting flow"),
      entry((byte)0x44, "Check setting FiO2"),
      entry((byte)0x45, "High-flow - switch to fresh gas control mode!"),
      entry((byte)0x4F, "Network communication lost"),
      entry((byte)0x50, "Oxygen module inoperable"),
      entry((byte)0x59, "No internal battery detected"),
      entry((byte)0x5A, "Power supply by battery"),
      entry((byte)0x5B, "No nebuliser"),
      entry((byte)0x5C, "Battery less than 2 min left"),
      entry((byte)0x5D, "Battery less than 5 min left"),
      entry((byte)0x66, "Apnea alarm disabled"),
      entry((byte)0x67, "Minute volume low alarm disabled"),
      entry((byte)0x68, "Tidal volume high alarm disabled"),
      entry((byte)0x69, "Distribution of alarms via SDC not possible"),
      entry((byte)0x6A, "Tube obstructed"),
      entry((byte)0x6C, "Check microfilter"),
      entry((byte)0x6D, "Power supply by external DC"),
      entry((byte)0x6E, "Ambient pressure high"),
      entry((byte)0x6F, "Ambient pressure low"),
      entry((byte)0x74, "Right atrial pressure < low limit"),
      entry((byte)0x75, "Right atrial pressure > high limit"),
      entry((byte)0x78, "Problems with right atrial pressure measurement"),
      entry((byte)0x7C, "Mattress temperature high"),
      entry((byte)0x7D, "Mattress temperature sensor inoperable"),
      entry((byte)0x7F, "Check patient"),
      entry((byte)0x80, "Radiant warmer faulty"),
      entry((byte)0x81, "Mattress temperature low"),
      entry((byte)0x8D, "Breathing system disconnected"),
      entry((byte)0x90, "Check neonatal flow sensor"),
      entry((byte)0x91, "Loss of data"),
      entry((byte)0x93, "Apnea ventilation"),
      entry((byte)0x94, "Check ventilator"),
      entry((byte)0x95, "Ventilator standby"),
      entry((byte)0x96, "Problems with PEEP control"),
      entry((byte)0x98, "Nebulizer is activated"),
      entry((byte)0x99, "Inspiration hold aborted"),
      entry((byte)0x9C, "Leakage detected"),
      entry((byte)0x9D, "Backup ventilation"),
      entry((byte)0x9E, "Expiration hold aborted"),
      entry((byte)0x9F, "Nebulization terminated"),
      entry((byte)0xA0, "Ventilator not in locked Position"),
      entry((byte)0xA1, "Problems with power supply"),
      entry((byte)0xA2, "Expiratory halothan > high limit"),
      entry((byte)0xA3, "Expiratory enflurane > high limit"),
      entry((byte)0xA4, "Expiratory isoflurane > high limit"),
      entry((byte)0xA5, "Expiratory desflurane > high limit"),
      entry((byte)0xA6, "Expiratory sevolurane > high limit"),
      entry((byte)0xA7, "Set tidal volume not attained"),
      entry((byte)0xA8, "Inspiratory flow measurement inoperable"),
      entry((byte)0xA9, "Setting could not be performed"),
      entry((byte)0xAB, "Confirm settings"),
      entry((byte)0xAC, "Fresh-gas flow too high"),
      entry((byte)0xAD, "Fresh-gas flow active"),
      entry((byte)0xAE, "Air trapping"),
      entry((byte)0xAF, "Oxygen cylinder open"),
      entry((byte)0xB0, "N2O cylinder open"),
      entry((byte)0xB1, "Air cylinder open"),
      entry((byte)0xB2, "N2O cylinder sensor not connected"),
      entry((byte)0xB3, "Air cylinder sensor not connected"),
      entry((byte)0xB4, "O2 cylinder sensor not connected"),
      entry((byte)0xB5, "Air cylinder empty or cylinder pressure low"),
      entry((byte)0xB6, "Inspiratory resistance >> resistance of test"),
      entry((byte)0xB7, "Expiratory resistance << resistance of test"),
      entry((byte)0xB8, "A setting, alarm limit or ventilation mode was changed, but the change was not  confirmed. If necessary, the user can adjust and confirm the setting again with  the rotary knob."),
      entry((byte)0xB9, "Automatic uptake control not operable"),
      entry((byte)0xBA, "Delivered volume greater set tidal volume due to minimum required PIP"),
      entry((byte)0xBB, "Insp. N2O < low limit"),
      entry((byte)0xBC, "Detected agent differs from selected type"),
      entry((byte)0xBD, "Insp. vol. agent > high limit"),
      entry((byte)0xBE, "DIVA module -I- or -II- is warming up"),
      entry((byte)0xBF, "Relearning ECG pattern"),
      entry((byte)0xC0, "Unable to relearn ECG pattern"),
      entry((byte)0xC1, "ECG inoperable"),
      entry((byte)0xC2, "RL-electrode failure"),
      entry((byte)0xC3, "V-plus electrode failure"),
      entry((byte)0xC4, "Cardiac output blood temperature > high limit"),
      entry((byte)0xC5, "Cardiac output blood temperature > low limit"),
      entry((byte)0xC6, "All alarms disabled"),
      entry((byte)0xC7, "Air fresh-gas flow measurement inoperable"),
      entry((byte)0xC8, "O2 fresh-gas flow measurement inoperable"),
      entry((byte)0xC9, "N2O fresh-gas flow measurement inoperable"),
      entry((byte)0xCA, "No air supply"),
      entry((byte)0xCB, "No N2O supply"), // DEPRECATED
      entry((byte)0xCC, "PEEP < low limit"),
      entry((byte)0xCD, "Set inspiratory pressure not attained"),
      entry((byte)0xCE, "Hose kinked"),
      entry((byte)0xCF, "Set tidal volume too high for connected hose"),
      entry((byte)0xD0, "Pressure relief valve opened"),
      entry((byte)0xD1, "Hose system defect"),
      entry((byte)0xD2, "Check MAC value"),
      entry((byte)0xD3, "Water trap expired?"),
      entry((byte)0xD4, "CO2 absorber depleted?"),
      entry((byte)0xD5, "CO2 absorber present?"),
      entry((byte)0xD6, "Hoses interchanged?"),
      entry((byte)0xD7, "Hoses incompatible?"),
      entry((byte)0xD8, "Accessory ID detection functions inoperable"),
      entry((byte)0xD9, "Breathing circuit expired?"),
      entry((byte)0xDA, "Set expiration time not attainable"),
      entry((byte)0xDB, "NMT TOF > high limit"),
      entry((byte)0xDC, "NMT TOF < low limit"),
      entry((byte)0xDD, "NMT initializing/NMT single out of range"),
      entry((byte)0xDE, "NMT check sensors and/or electrodes"),
      entry((byte)0xDF, "NMT temperature out of range"),
      entry((byte)0xE0, "Bispectral index high"),
      entry((byte)0xE1, "Bispectral index low"),
      entry((byte)0xE2, "Bispectral calculation not possible"),
      entry((byte)0xE3, "Check BIS sensor"),
      entry((byte)0xE4, "BISX out of range"),
      entry((byte)0xE5, "SmartCare: patient session aborted"),
      entry((byte)0xE6, "SmartCare: inoperable / patient session terminated"),
      entry((byte)0xE7, "SmartCare: Central Hypoventilation"),
      entry((byte)0xE8, "SmartCare: Persistent Tachypnea"),
      entry((byte)0xE9, "SmartCare: Unexplained Hyperventilation"),
      entry((byte)0xEA, "SmartCare: Reduce PEEP if possible"),
      entry((byte)0xEB, "SmartCare: SBT successful"),
      entry((byte)0xEC, "Ejector inoperable"),
      entry((byte)0xED, "Constant CO2 offset"),
      entry((byte)0xEF, "Autoflow VT too low"),
      entry((byte)0xF1, "Pilot lines switched"),
      entry((byte)0xF2, "Breathing hoses missing"),
      entry((byte)0xF3, "SmartCare: Reduce FiO2 if  possible"),
      entry((byte)0xF4, "Mean Airway Pressure < low limit"),
      entry((byte)0xF7, "Airway pressure high (HFO)"),
      entry((byte)0xF8, "Tidal volume < low Limit"),
      entry((byte)0xF9, "Plow > high limit"),
      entry((byte)0xFA, "Plow < low limit"),
      entry((byte)0xFB, "Delivered volume limited by VTmax"),
      entry((byte)0xFC, "Air entrainment"),
      entry((byte)0xFD, "Ventilation pause exceeded"),
      entry((byte)0xFE, "Power supply by internal battery"),
      entry((byte)0xFF, "In O2 therapy the set flow cannot be reached due to high resistance.")
    );

    public static Map<Byte, String> MedibusXTextMessages = Map.<Byte, String>ofEntries(
      entry((byte)0x01, "Mode VC-CMV (volume-controlled, continuous mandatory  ventilation)"),
      entry((byte)0x02, "Mode VC-AC (volume-controlled, assist controlled ventilation)"),
      entry((byte)0x06, "Mode VC-SIMV (volume-controlled, synchronized intermittent  mandatory ventilation)"),
      entry((byte)0x0A, "Mode SPN-CPAP (spontaneous ventilation, continuous  positive airway pressure)"),
      entry((byte)0x0C, "Mode VC-MMV (volume-controlled, mandatory minute  ventilation)"),
      entry((byte)0x0D, "Mode PC-MMV (pressure-controlled, mandatory minute  ventilation)"),
      entry((byte)0x0E, "Mode PC-BIPAP (pressure-controlled, bi-phasic positive  airway pressure)"),
      entry((byte)0x11, "Automatic apnea ventilation active"),
      entry((byte)0x12, "Device in PRODUCT TEST mode"),
      entry((byte)0x13, "Air mode is active"),
      entry((byte)0x14, "Skin mode is active"),
      entry((byte)0x15, "Oxygen control is active"),
      entry((byte)0x16, "Humidity control is active"),
      entry((byte)0x18, "Mode PC-SIMV (pressure-controlled, synchronized intermittent  mandatory ventilation"),
      entry((byte)0x1A, "Mode PC-APRV (pressure-controlled, airway pressure release  ventilation)"),
      entry((byte)0x1B, "Mode PC-HFO (pressure-controlled, high frequency  oscillation)"),
      entry((byte)0x1C, "Suction maneuver active"),
      entry((byte)0x1D, "Low-flow maneuver active"),
      entry((byte)0x1E, "Ventilator is in standby mode"),
      entry((byte)0x20, "Device is in adult mode"),
      entry((byte)0x21, "Device is in neonatal mode"),
      entry((byte)0x22, "Selected CO2 unit is mmHg"),
      entry((byte)0x23, "Selected CO2 unit is kPa"),
      entry((byte)0x24, "Selected CO2 unit is %"),
      entry((byte)0x25, "Halothane selected or detected"),
      entry((byte)0x26, "Enflurane selected or detected"),
      entry((byte)0x27, "Isoflurane selected or detected"),
      entry((byte)0x28, "Desflurane selected or detected"),
      entry((byte)0x29, "Sevoflurane selected or detected"),
      entry((byte)0x2A, "No anesthesia agent selected nor detected"),
      entry((byte)0x2B, "Ventilation mode man./spont."),
      entry((byte)0x2C, "Selected language"),
      entry((byte)0x35, "Mode SPN-PPS (spontaneous, proportional pressure support)"),
      entry((byte)0x36, "Ventilation mode FRESH GAS EXTERNAL"),
      entry((byte)0x37, "Selected carrier gas is air"),
      entry((byte)0x38, "Selected carrier gas is N2O"),
      entry((byte)0x3A, "Device is in pediatric mode"),
      entry((byte)0x3B, "Manual mode is active"),
      entry((byte)0x3C, "Open care therapy is active"),
      entry((byte)0x3D, "Photo therapy is active"),
      entry((byte)0x3E, "Mode PC-PSV (pressure controlled, pressure support  ventilation)"),
      entry((byte)0x42, "Patient is a female"),
      entry((byte)0x43, "Patient is a male"),
      entry((byte)0x45, "End-expiratory control of anesthesia gas active"),
      entry((byte)0x47, "Mode PC-AC (pressure controlled, assisted-controlled)"),
      entry((byte)0x48, "Device configured for intubated patient ventilation"),
      entry((byte)0x49, "Device configured for mask ventilation"),
      entry((byte)0x4A, "2nd agent halothane selected or detected"),
      entry((byte)0x4B, "2nd agent enflurane selected or detected"),
      entry((byte)0x4C, "2nd agent isoflurane selected or detected"),
      entry((byte)0x4D, "2nd agent desflurane selected or detected"),
      entry((byte)0x4E, "2nd agent sevoflurane selected or detected"),
      entry((byte)0x4F, "No 2nd anesthesia agent selected nor detected"),
      entry((byte)0x50, "Mattress temperature control is active"),
      entry((byte)0x51, "Kangaroo mode is active"),
      entry((byte)0x53, "Device is performing leakage test"),
      entry((byte)0x54, "Device is in standby mode"),
      entry((byte)0x55, "Low pressure oxygenation active"),
      entry((byte)0x56, "Selected agent unit is kPa"),
      entry((byte)0x57, "Selected agent unit is %"),
      entry((byte)0x58, "HLM mode active"),
      entry((byte)0x5C, "Pressure support added to current ventilation mode"),
      entry((byte)0x5D, "Audio pause active"),
      entry((byte)0x5E, "AutoFlow added to current ventilation mode"),
      entry((byte)0x5F, "Fresh-gas control of anaesthesia gas active"),
      entry((byte)0x60, "First name of patient"),
      entry((byte)0x61, "Last name of patient"),
      entry((byte)0x62, "Patient monitoring is in simulation mode"),
      entry((byte)0x63, "Ventilator was switched off by emergence switch \"Anesthesia  ventilator OFF\""),
      entry((byte)0x64, "Trigger level normal"),
      entry((byte)0x65, "Trigger level sensitive"),
      entry((byte)0x67, "Apnea detection disabled"),
      entry((byte)0x68, "Tube type endotracheal"),
      entry((byte)0x69, "Volume guarantee added to current ventilation mode"),
      entry((byte)0x6A, "Mode PC-CMV (pressure controlled, continuous mandatory  ventilation)"),
      entry((byte)0x6B, "Mode O2 therapy"),
      entry((byte)0x6C, "Abdominal external trigger"),
      entry((byte)0x6D, "Automatic tube compensation (ATC) added to current  ventilation mode"),
      entry((byte)0x6E, "Expiratory automatic tube compensation (ATC) enabled"),
      entry((byte)0x6F, "Inspiratory automatic tube compensation (ATC) enabled"),
      entry((byte)0x70, "Tube type tracheostoma"),
      entry((byte)0x71, "Apnea ventilation enabled"),
      entry((byte)0x72, "Apnea ventilation auto-return enabled"),
      entry((byte)0x73, "Screen is locked"),
      entry((byte)0x74, "Volume support added to current ventilation mode"),
      entry((byte)0x75, "AutoRelease added to current ventilation mode"),
      entry((byte)0x76, "Active humid unheated"),
      entry((byte)0x77, "Active humid heated"),
      entry((byte)0x78, "HME / Filter"),
      entry((byte)0x79, "SmartCare therapy phase: adapting"),
      entry((byte)0x7A, "SmartCare therapy phase: observing"),
      entry((byte)0x7B, "SmartCare therapy phase: maintaining"),
      entry((byte)0x7C, "SmartCare diagnosis: normal ventilation"),
      entry((byte)0x7D, "SmartCare diagnosis: hyperventilation"),
      entry((byte)0x7E, "SmartCare diagnosis: hypoventilation"),
      entry((byte)0x7F, "SmartCare diagnosis: insufficient ventilation"),
      entry((byte)0x80, "SmartCare diagnosis: tachypnea"),
      entry((byte)0x81, "SmartCare diagnosis: severe tachypnea"),
      entry((byte)0x82, "SmartCare diagnosis: unexplained hyperventilation"),
      entry((byte)0x83, "SmartCare diagnosis: central hypoventilation"),
      entry((byte)0x84, "SmartCare: patient with COPD"),
      entry((byte)0x85, "SmartCare: patient with neurologic disorder"),
      entry((byte)0x86, "SmartCare: night rest requested"),
      entry((byte)0x87, "Sigh added to current ventilation mode"),
      entry((byte)0x88, "Cuvette type: disposable"),
      entry((byte)0x89, "Cuvette type: reusable"),
      entry((byte)0x8A, "Hose type: disposable"),
      entry((byte)0x8B, "Hose type: reusable"),
      entry((byte)0x8C, "Hose size: adult"),
      entry((byte)0x8D, "Hose size: pediatric"),
      entry((byte)0x8E, "Variable PS added to current ventilation mode"),
      entry((byte)0x8F, "SmartCare zone of respiratory comfort: Customization active"),
      entry((byte)0x90, "Overall device check result fully functional"),
      entry((byte)0x91, "Overall device check result conditionally functional"),
      entry((byte)0x92, "Overall device check result non functional"),
      entry((byte)0x9F, "Tracheal pressure calculation enabled as real-time value  (independent of ATC adjunct)"),
      entry((byte)0xA0, "Date and time of last self test execution"),
      entry((byte)0xA1, "Date and time of last leakage test execution"),
      entry((byte)0xA2, "Warm-up mode is active"),
      entry((byte)0xA3, "Weaning mode is active"),
      entry((byte)0xA4, "Tolerate cooling procedure is active"),
      entry((byte)0xA5, "Closed care therapy is active"),
      entry((byte)0xA6, "Multi-step recruitment is active"),
      entry((byte)0xA7, "One-step recruitment is active"),
      entry((byte)0xA8, "CPR ventilation is paused"),
      entry((byte)0xA9, "Check the calibration status of the Medibus.X device as some  parameters may not be calibrated and therefore the  measurements might not achieve the nominal accuracy"),
      entry((byte)0xAA, "Active humidification, inspiratory heated"),
      entry((byte)0xAB, "Active humidification, dual heated")
    );


    public static Map<Byte, String> MedibusXDeviceSettings = Map.<Byte, String>ofEntries(
      entry((byte)0x01, "Inspiratory oxygen fraction, FiO2"),
      entry((byte)0x02, "Inspiratory flow, Flowi"),
      entry((byte)0x03, "Time interval between sighs, Interval sigh"),
      entry((byte)0x04, "Inspiratory tidal volume, VTi"),
      entry((byte)0x05, "Inspiratory time, Ti"),
      entry((byte)0x06, "Expiratory time, Te"),
      entry((byte)0x07, "I : E I part"),
      entry((byte)0x08, "I : E E part"),
      entry((byte)0x09, "Respiratory rate, RR"),
      entry((byte)0x0A, "Minimal provided respiratory rate, RRmin"),
      entry((byte)0x0B, "Positive end-expiratory pressure, PEEP"),
      entry((byte)0x0C, "Additional intermittent PEEP for sighs, ΔintPEEPsigh"),
      entry((byte)0x0D, "Lower pressure level during APRV, Plow"),
      entry((byte)0x0E, "Upper pressure level during APRV, Phigh"),
      entry((byte)0x0F, "Time of lower pressure level during APRV, Tlow"),
      entry((byte)0x10, "Time of upper pressure level during APRV, Thigh"),
      entry((byte)0x11, "Apnea alarm time, Tapn"),
      entry((byte)0x12, "Pressure amplitude above PEEP in Pressure Support, ΔPsupp"),
      entry((byte)0x13, "Pressure limitation, Pmax"),
      entry((byte)0x14, "Number of respiratory cycles per sigh phase, Cycles sigh"),
      entry((byte)0x17, "P01 repetition interval, Interval P0.1"),
      entry((byte)0x18, "Delay for minute volume high alarm, MVhigh delay"),
      entry((byte)0x19, "Delay for minute volume low alarm, MVlow delay"),
      entry((byte)0x1A, "Air temperature, T Air"),
      entry((byte)0x1B, "Skin temperature, T Skin"),
      entry((byte)0x1C, "Relative humidity, Humidity"),
      entry((byte)0x24, "Oxygen concentration, O2"),
      entry((byte)0x27, "Plateau time in % of inspiratory time, % Tplat"),
      entry((byte)0x29, "Flow trigger threshold, Trigger"),
      entry((byte)0x2A, "Frequency during HFO, fhf"),
      entry((byte)0x2E, "Pressure rise time, Slope"),
      entry((byte)0x2F, "Fresh-gas flow, FG flow"),
      entry((byte)0x3C, "Flow assist during PPS ventilation, Flow Assist"),
      entry((byte)0x3D, "Volume assist during PPS ventilation, Vol. Assist"),
      entry((byte)0x3E, "Radiant warmer power, Heater rad"),
      entry((byte)0x3F, "Mattress temperature, T Matt"),
      entry((byte)0x40, "Inspiratory tidal volume, VTi"),
      entry((byte)0x42, "Respiratory rate for apnea ventilation, RRapn"),
      entry((byte)0x44, "Tidal volume for apnea ventilation, VTapn"),
      entry((byte)0x45, "Inspiratory pressure, Pinsp"),
      entry((byte)0x46, "Compensation rate during ATC, % comp"),
      entry((byte)0x47, "Inner diameter of the endotracheal/tracheostoma tube, Ø tube"),
      entry((byte)0x49, "Ratio of inspiration to expiration I:E"),
      entry((byte)0x4A, "Age"),
      entry((byte)0x4B, "Weight, Wt"),
      entry((byte)0x4E, "Disconnection alarm time, Tdiscon"),
      entry((byte)0x4F, "Flow Acceleration, Flow Acc"),
      entry((byte)0x55, "Volatile anesthetic agent concentration in the fresh gas, FG VA"),
      entry((byte)0x56, "End-tidal volatile agent concentration, etVA"),
      entry((byte)0x5B, "Isoflurane concentration in the fresh gas, FG Iso"),
      entry((byte)0x5C, "End-tidal isoflurane concentration, etIso"),
      entry((byte)0x5D, "Desflurane concentration in the fresh gas, FG Des"),
      entry((byte)0x5E, "End-tidal desflurane concentration, etDes"),
      entry((byte)0x5F, "Sevoflurane concentration in the fresh gas, FG Sev"),
      entry((byte)0x60, "End-tidal sevoflurane concentration, etSev"),
      entry((byte)0x61, "Oxygen concentration in the fresh gas, FG O2"),
      entry((byte)0x62, "Minimum fresh-gas flow, MinFG flow"),
      entry((byte)0x63, "Maximal inspiratory time for flow cycled strokes, Timax"),
      entry((byte)0x65, "Constant flow during O2 therapy, Const flow"),
      entry((byte)0x66, "mean airway pressure during HFO, MAPhf"),
      entry((byte)0x67, "Inspiratory part of I:E ratio during HFO, I (I:Ehf)"),
      entry((byte)0x68, "Expiratory part of I:E ratio during HFO, E (I:Ehf)"),
      entry((byte)0x69, "Pressure amplitude during HFO, Ampl hf"),
      entry((byte)0x6A, "Tidal volume during HFO, VThf"),
      entry((byte)0x6B, "Respiratory rate of sighs during HFO, RRsigh"),
      entry((byte)0x6C, "Inspiratory time of sighs during HFO, Tisigh"),
      entry((byte)0x6D, "Inspiratory pressure of sighs during HFO, Psigh"),
      entry((byte)0x6E, "Tidal volume during apnea ventilation, VTapn"),
      entry((byte)0x6F, "Ideal body weight, IBW"),
      entry((byte)0x72, "Inspiratory termination criterion based on peak inspiratory flow, Insp. term."),
      entry((byte)0x73, "Expiratory termination criterion during APRV/AutoRelease, Exp. term."),
      entry((byte)0x74, "Ideal body weight in SmartCare, SC-Weight"),
      entry((byte)0x75, "Start of night rest in SmartCare, SC-start of rest"),
      entry((byte)0x76, "End of night rest in SmartCare, SC-end of rest"),
      entry((byte)0x78, "Pressure rise time of sighs during HFO, Slopesigh"),
      entry((byte)0x79, "FiO2 in SmartCare - upper limit, SC-FiO2 high"),
      entry((byte)0x7A, "PEEP in SmartCare - upper limit, SC-PEEPmax"),
      entry((byte)0x7B, "Pressure variability, Press. var."),
      entry((byte)0x7D, "Maximum time of low pressure level during APRV/AutoRelease, Tlow max"),
      entry((byte)0x7E, "Spontaneous respiratory rate in SmartCare - lower limit, SC-RRspon low"),
      entry((byte)0x7F, "Spontaneous respiratory rate in SmartCare - upper limit, SC-RRspon high"),
      entry((byte)0x80, "Tidal volume in SmartCare - lower limit, SC-VT low"),
      entry((byte)0x81, "End-tidal CO2 in SmartCare - upper limit, SC-etCO2high"),
      entry((byte)0x82, "Patient height in SmartCare, SC-Height"),
      entry((byte)0x83, "Patient height, Ht"),
      entry((byte)0x84, "Maximal peak to peak pressure during HFO, Ampl hf max"),
      entry((byte)0x85, "Volume limitation, VTmax"),
      entry((byte)0x86, "Manual inspiratory pressure for Neonates during NIV - Non-Invasive Ventilation,  PmanInsp"),
      entry((byte)0x87, "Maximum time of pressure for manual inspiration pressure for Neonates during NIV Non-Invasive Ventilation, TmanInsp"),
      entry((byte)0x88, "Maximum airway pressure in Smart Ventilation Control, SVC-Pmax"),
      entry((byte)0x8A, "Airway access"),
      entry((byte)0x8B, "Lung mechanics in Smart Ventilation Control, Lung mechanics"),
      entry((byte)0x8C, "Ventilation goal of Smart Ventilation Control, Ventilation goal")
    );
}
